### PR TITLE
Add test

### PR DESCRIPTION
**Pull request by IceTank**

### CODE REVIEW

**Comment by IceTank** [comment]
Possible test 

- [x] Goals
  Goto
  setGoal
  GoalBlock
  GoalNear
  GoalXZ
  GoalNearXZ
  GoalY
  GoalGetToBlock
  GoalCompositeAny
  GoalCompositeAll
  GoalInvert
  GoalFollow
  GoalPlaceBlock
  GoalBreakBlock
- [ ] Movement
  countScaffoldingItems
  getScaffoldingItem
  getBlock
  safeToBreak
  safeOrBreak
  getMoveJumpUp
  getMoveForward
  getMoveDiagonal
  getLandingBlock
  getMoveDropDown
  getMoveDown
  getMoveUp
  getMoveParkourForward
  getNeighbors
- [ ] Events
  goal_reached
  goal_updated
  goal_reset
  path_stop
- [ ] Util functions
  Goto
  bestHarvestTool
  getPathTo
  isMoving
  isMining
  isBuilding
- [ ] Physics
  simulateUntil
  simulateUntilNextTick
  simulateUntilOnGround
  canStraightLine
  canStraightLineBetween
  canSprintJump
  canWalkJump
  getReached
  getController

**Comment by IceTank** [comment]
Tests are not working right now. The Movement test thats failing is most likely due to a pathfinder bug. I have no idea why the other test is failing.

**Comment by rom1504** [comment]
is this ready to merge?

**Comment by IceTank** [comment]
Test failing right now. I have to fix that. But it should be ready to be merged after this. I still want to expand and improve the tests some more in the future but this should work for some basic test already.

**Comment by rom1504** [comment]
@IceTank let's finish this :)

**Review by Karang — APPROVED** [review]
LGTM

**Pull request merged**
