### PR TITLE
Replace control logic by physic simulation, sprint and advanced parkour

### LINKED ISSUE #80: Sprint usage
An option should allow the bot to use sprint to go to its destination.

### PR DESCRIPTION
**Pull request by Karang**
Inspired by https://github.com/mat-1/mineflayer-baritone with some simplifications.

Closes #80, #70, #14, #44

### CODE REVIEW

**Comment by rom1504** [comment]
Would be really great to have some automated benchmark measuring how fast to go from A to B. That way it would be easy to see the consequence of this kind of PR

**Comment by Karang** [comment]
Yeah testing it manually is not really practical. There are 3 aspects that needs to be tested for this kind of changes:
* computation time (or number of visited nodes for fixed timeout)
* path quality (did we found a path to destination?)
* path execution (can the bot follow the path without falling ?)
And of course, it is better if the path includes weird blocks (water, half blocks, snow layers, fences, etc...)

**Comment by rom1504** [comment]
I think it would work to have tests like in mineflayer with node-minecraft-wrap, to use a flat world and then do a bunch of set block to try various scenario.
Then make the bot do the pathfinding and measure these things

**Comment by Karang** [comment]
Yeah that's the basic idea, but a bunch of setBlocks will not be practical, we'll need a way to paste schematics or load a preconfigured test world. This could also allow more members to contribute to tests by just providing a schematic with the configuration that fails.

**Comment by rom1504** [comment]
Yeah that sounds pretty good. We could do this as part of a package as
suggested by @TheDudeFromCI there
https://github.com/PrismarineJS/mineflayer/issues/1422

**Review by rom1504 — APPROVED** [review]
lgtm
if you tested it manually and it works, let's merge ?

**Comment by Karang** [comment]
> lgtm
> if you tested it manually and it works, let's merge ?

I'm still testing edge cases, I want to be sure it works properly. I'll merge it when its ready.

**Pull request merged**
