### PR TITLE
Add infiniteLiquidDropdownDistance boolean

### PR DESCRIPTION
**Pull request by IceTank**
to movement

### CODE REVIEW

**Comment by rom1504** [comment]
please explain what this is doing

you can take this comment in general: PR should be composed of a code change *and* an explanation on why you think this is good
reverse engineering your change to try to guess your intention isn't time well spent for the reviewer

**Comment by SaubereSache** [comment]
If `infiniteLiquidDropdownDistance` isn't set, prevents the bot from jumping more than `maxDropDown` into liquids.

**Comment by rom1504** [comment]
@IceTank can you add to doc in readme ?

**Comment by IceTank** [comment]
To Clarify the pull request:
This pull request adds an option to change the behavior of maxDropDown. Pathfinder currently ignores maxDropDown (distance) when the landing block is water (or a liquid and safe). With this new setting changed to false the max falling distance is always maxDropDown distance regardless off the landing block.

About the comment from SaubereSache. I think it should work (?). I have not tested it yet but I will update the pull request when I know if it is working.

**Pull request merged**
