### PR TITLE
Goal break block option fix

### PR DESCRIPTION
**Pull request by IceTank**

### CODE REVIEW

**Comment by SaubereSache** [comment]
Incorrect, [readme.md](https://github.com/PrismarineJS/mineflayer-pathfinder/blob/master/readme.md#goalplaceblockpos-world-options) describes the following:
   * range - maximum distance from the clicked face
   * faces - the directions of the faces the player can click
   * facing - the direction the player must be facing
   * facing3D - boolean, facing is 3D (true) or 2D (false)
   * half - top or bottom, the half that must be clicked

**Comment by rom1504** [comment]
looks like this needs rebasing + fixing

**Comment by SaubereSache** [comment]
I'll do it ^^

**Comment by SaubereSache** [comment]
https://github.com/PrismarineJS/mineflayer-pathfinder/pull/238

**Pull request closed without merging**
